Neos:
  Flow:
    mvc:
      routes:
        Weissheiten.Flow.WiFiGuestCredentialsProvider:
          variables:
            prefix: wifivoucher
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Weissheiten.Flow.WiFiGuestCredentialsProvider':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Weissheiten\Flow\WiFiGuestCredentialsProvider\Controller\.*'
  Neos:
    modules:
      management:
        submodules:
          WiFiVoucher:
            label: 'WiFi Voucher'
            controller: Weissheiten\Flow\WiFiGuestCredentialsProvider\Controller\ReportController
            description: 'WiFi Voucher Reports'
            icon: fas fa-wifi
            privilegeTarget: 'Weissheiten.Flow.WiFiGuestCredentialsProvider:ReportActions'
            additionalResources:
              styleSheets:
                - 'resource://Weissheiten.Flow.WiFiGuestCredentialsProvider/Public/Css/wifiguestcredentialsprovider.css'
                - 'resource://Neos.Neos/Public/Styles/Neos.css'
Weissheiten:
  Flow:
    WiFiGuestCredentialsProvider:
      alertEmail:
        active: true
        tresholds:
          - 100
          - 75
          - 50
          - 25
          - 1
        from:
          email: 'office@billardcafe.at'
          name: 'Billardcafe WiFi Voucher System'
        subject: 'WiFi Voucher System | Vorrat an ungenutzten WiFiVouchern im System ist niedrig'
        to:
          webmaster:
            email: 'webmaster@billardcafe.at'
            name: 'Florian Weiss'
        cc:
          itsupport:
            email: 'michael.beneder@billardcafe.at'
            name: 'Michael Beneder'
        text: 'Vorsicht: Der Vorrat an ungenutzten WiFiVouchern beträgt %u Stück - bitte stellen Sie zeitnah neue Voucher zur Verfügung!'